src/extract.ts
test/data/extract/benchmarkjs_output.txt
test/extract.ts

benchmarkjs may have results with decimal dot
For example:
`createObjectBuffer with 200 comments x 81.61 ops/sec ±1.70% (69 runs sampled)`

Support benchmark results with decimal dot

---

src/extract.ts

Hi! I am using github action for benchmarking! Thanks for the great library.
I am using fixture filenames as benchmark name so they will contain non `\w` in the test name like `fixture.ext`.
Changing `[\w/]` to `\S` allow more names as test.
Example failing case https://github.com/HerringtonDarkholme/vue-compiler/runs/3774871750?check_suite_focus=true

fix: allow more test name

---

README.md

The new custom benchmark types are missing from the README. This simply adds them.

Add new custom types to README

---

src/extract.ts
test/data/extract/criterion_output.txt
test/extract.spec.ts

When using Criterion for Rust benchmarks, you can use any string as a benchmark name, but this action doesn't allow for this option. We have a repo with strings for these benchmark names, and we would need this feature.

Added option to use Rust benchmark names with spaces

---

src/extract.ts
test/data/extract/cargo_output2.txt
test/extract.spec.ts

fix trailing whitespace characters in cargo benchmarks

---

CHANGELOG.md
src/git.ts
src/write.ts
test/git.spec.ts
test/write.spec.ts

With #38 being open for over 1.5 year, I've taken the liberty to rebase the commit against the main branch, so it can be considered again.
This should:
* Close #19 
* Close #58 
* Close #38

Fetch gh-pages branch using github token

---

README.md

The extra brackets around the short-links meant that the links weren't being rendered correctly.

Fix a couple errant links for Benchmark.NET

---

.github/workflows/benchmarkdotnet.yml
.github/workflows/benchmarkjs.yml
.github/workflows/catch2.yml
.github/workflows/ci-results-repo.yml
.github/workflows/ci.yml
.github/workflows/cpp.yml
.github/workflows/criterion-rs.yml
.github/workflows/go.yml
.github/workflows/julia.yml
.github/workflows/pytest.yml
.github/workflows/rust.yml
.gitignore
CHANGELOG.md
README.md
scripts/ci_validate_modification.ts
src/config.ts
src/git.ts
src/write.ts
test/git.spec.ts
test/write.spec.ts

Rebase of #37. Closes #36. Closes #61. Closes #87.
I don't know typescript, so feel free to take it and run with it.

Implement deploy to another repository

---

README.md

Hi,
I was flustered by the documentation of the `save-data-file` argument. It states that if `save-data-file` is `true`, the current benchmark will **not** be saved to the external data file, which doesn't make much sense given the name of the argument. After running the action in one of my repos, I realized that this is a mistake in the documentation. 
Because this is such a small fix, I didn't bother raising an issue beforehand, hope that's alright.

Fix for small documentation error for save-data-file argument

---

.github/workflows/rust.yml
README.md
src/config.ts
src/index.ts
src/write.ts
test/write.spec.ts

Provide support for PR Summary for benchmark output.
Refer: https://github.com/benchmark-action/github-action-benchmark/issues/136

feat: support pr summary for benchmark output

---

src/write.ts

Currently we are providing the `commit` object as is instead of the
commit ID which is the actual string.
Refer for example: https://github.com/infinyon/fluvio/actions/runs/4347865829

fix: use `commit.id` over `commit` object

---

action.yml
src/config.ts
src/extract.ts
test/extract.spec.ts
test/write.spec.ts

The ref will be used preferentially (if specified) when looking up the details of the commit to record the results against.
Why:
When used to record results from a performance test run triggered by a comment on a PR, the results were recorded against the head commit of main, not the tested commit. The workflow checked out the PR's ref and ran tests against this. This change allows users to specify the tested ref to record benchmark results against.
Example usage:
```
with:
ref: refs/pull/${{ github.event.issue.number }}/head
```
Closes #157

Enable user to specify the git ref being tested

---

src/git.ts

GitHub Enterprise Server 3.7 or earlier fails to resolve the server URL because the schedule event payload does not include repository.
Since the server URL can be got with the GITHUB_SERVER_URL environment variable, it is now referenced if it cannot be got from payload.
https://docs.github.com/en/enterprise-server@3.8/admin/release-notes
> For scheduled runs of GitHub Actions workflows, users will see additional information about the repository, organization, and enterprise within the payload for github.event.

getServerUrl refers to the GITHUB_SERVER_URL environment variable

---

package-lock.json
package.json
src/extract.ts
src/write.ts
test/extract.spec.ts
test/write.spec.ts

getCommitFromGitHubAPIRequest is currently only supported on api.github.com. Therefore, if the event is GitHub Enterprise and the commit cannot be retrieved by payload, it will fail to retrieve the commit.
(e.g. scheduled event)
To fix this, the following fixes have been made.
* Fix to use [getOctokit](https://github.com/actions/toolkit/blob/main/packages/github/src/github.ts#L15)
* .getOctokit refer to GITHUB_API_URL (https://github.com/actions/toolkit/blob/main/packages/github/src/internal/utils.ts#L24)
* upgraded actions/github to use getOctokit
* Fix code and tests for actions/gihub version upgrade

Fixed getCommitFromGitHubAPIRequest to refer to GITHUB_API_URL

---

.github/workflows/ci-results-repo.yml
.github/workflows/ci.yml
.github/workflows/commit-comment.yml
.github/workflows/go.yml
.github/workflows/minimal.yml
README.md
examples/go/fib_test.go
examples/go/go.mod
src/extract.ts
test/data/extract/go_output.txt
test/extract.spec.ts

Address the comments of this PR: https://github.com/benchmark-action/github-action-benchmark/pull/119

feat: extract multiple metrics from golang benchmarks

---

.github/workflows/benchmarkdotnet.yml
.github/workflows/benchmarkjs.yml
.github/workflows/catch2.yml
.github/workflows/ci-results-repo.yml
.github/workflows/ci.yml
.github/workflows/commit-comment.yml
.github/workflows/cpp.yml
.github/workflows/criterion-rs.yml
.github/workflows/go.yml
.github/workflows/java.yml
.github/workflows/julia.yml
.github/workflows/minimal.yml
.github/workflows/pytest.yml
.github/workflows/rust.yml
README.md

* update actions/checkout to v4
* update actions/cache to v4
* update actions/setup-node to v4
* remove unnecessary usages of action/cache for node
* update actions/setup-python to v5
* update actions/setup-dotnet to v3
* update actions/setup-java to v4

chore: update actions/*

---

src/index.ts
src/write.ts

* move summary logic into writeBenchmark function so that we only clone the separate repo once
fixes #213

fix: 213 summary-always and gh-repository don't work together

---

.github/workflows/ci-results-repo.yml
.github/workflows/ci.yml

* move saving of previous benchmarks results further in the workflow files so that there is a smaller window when other action might push new changes

fix: improve flaky CI runs

---

.github/workflows/ci-results-repo.yml
.github/workflows/ci.yml
.github/workflows/cpp.yml
.github/workflows/rust-criterion-rs.yml
.gitignore
CHANGELOG.md
src/write.ts

* sort jobs in ci workflows
* add missing benches to ci jobs
* rename Criterion bench to distinguish between default Rust and Criterion benchmarks
fixes #231

fix: 231 rust bench not comparing to baseline

---

README.md

The feature name "PR Summary" is confusing, as it didn't actually create a comment in PRs. Instead, it only creates an action summary.

Rename "PR Summary" into "Job Summary"

---

.github/workflows/validate-action-typings.yml
action-types.yml

Add typings using https://github.com/typesafegithub/github-actions-typing, so that other tools can make use of them.

Add typings and validation workflow

---

examples/benchmarkdotnet/README.md

- Update outdated links.
- Fix incorrect naming (e.g. for the NuGet package)
- Remove dangling quote.

Update C# README

---

src/extract.ts
test/__snapshots__/extract.spec.ts.snap
test/data/extract/cargo_output_units.txt
test/extract.spec.ts

Previously the unit 'ns/iter' was hardcoded:
```
test bench_fib_10 ... bench:         148.70 ns/iter (+/- 2.21)
test bench_fib_20 ... bench:      18,794.12 ns/iter (+/- 440.25)
```
This PR allows any unit:
```
test cmov ... bench:        2835 cycles/iter (+/- 14)
test cmov2 ... bench:        2845 cycles/iter (+/- 19)
test mov ... bench:        1508 cycles/iter (+/- 17)
```

feat: allow to parse generic cargo bench/criterion units

---

src/write.ts

Alerts are currently generated by throwing an exception. This means that all code that comes after that exception is skipped, including generating the Action summary.
We can easily fix this, by generating the summary first.
Longer term, we might want to reconsider the code style here. An exception should model something exceptional happening in our code. Seeing bad benchmark numbers is not exceptional. It's what this tool is supposed to handle.
Closes https://github.com/benchmark-action/github-action-benchmark/issues/254

Add summary even when failure threshold is surpassed

---

CHANGELOG.md
package-lock.json
package.json
src/extract.ts
test/__snapshots__/extract.spec.ts.snap
test/data/extract/customSmallerIsBetter_output2.json
test/extract.spec.ts

* add Zod schema for BenchmarkResult
* parse custom benchmark output to make sure it conforms to schema
* allow for coercion
fixes #322

fix: improve validation for custom benchmarks
